// Auto-generated by `mcp__plugin_supabase_supabase__generate_typescript_types`.
// Regenerate after any schema migration — do not hand-edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.4"
  }
  public: {
    Tables: {
      jobs: {
        Row: {
          completed_at: string | null
          created_at: string | null
          error_message: string | null
          id: string
          input_file_path: string | null
          job_type: string
          metadata: Json | null
          org_id: string
          output_file_path: string | null
          progress: number | null
          started_at: string | null
          status: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string | null
          error_message?: string | null
          id?: string
          input_file_path?: string | null
          job_type: string
          metadata?: Json | null
          org_id: string
          output_file_path?: string | null
          progress?: number | null
          started_at?: string | null
          status?: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string | null
          error_message?: string | null
          id?: string
          input_file_path?: string | null
          job_type?: string
          metadata?: Json | null
          org_id?: string
          output_file_path?: string | null
          progress?: number | null
          started_at?: string | null
          status?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "orgs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_org_summary_view"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "jobs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      meal_history: {
        Row: {
          calories: number | null
          carbs: number | null
          created_at: string
          fat: number | null
          health_score: number | null
          id: string
          image_url: string | null
          meal_name: string | null
          protein: number | null
          report_data: Json | null
          user_id: string
        }
        Insert: {
          calories?: number | null
          carbs?: number | null
          created_at?: string
          fat?: number | null
          health_score?: number | null
          id?: string
          image_url?: string | null
          meal_name?: string | null
          protein?: number | null
          report_data?: Json | null
          user_id: string
        }
        Update: {
          calories?: number | null
          carbs?: number | null
          created_at?: string
          fat?: number | null
          health_score?: number | null
          id?: string
          image_url?: string | null
          meal_name?: string | null
          protein?: number | null
          report_data?: Json | null
          user_id?: string
        }
        Relationships: []
      }
      memberships: {
        Row: {
          created_at: string | null
          id: string
          org_id: string
          role: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          org_id: string
          role?: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          org_id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "orgs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_org_summary_view"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      orgs: {
        Row: {
          created_at: string | null
          created_by: string | null
          id: string
          is_active: boolean | null
          name: string
          slug: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          slug: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          slug?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orgs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "user_org_summary_view"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "orgs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      plans: {
        Row: {
          created_at: string | null
          description: string | null
          display_name: string
          features: Json | null
          id: string
          is_active: boolean | null
          name: string
          price_monthly: number | null
          price_yearly: number | null
          quota_images_per_day: number | null
          quota_storage_gb: number | null
          quota_text_requests_per_day: number | null
          quota_videos_per_day: number | null
          stripe_price_id_monthly: string | null
          stripe_price_id_yearly: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          display_name: string
          features?: Json | null
          id?: string
          is_active?: boolean | null
          name: string
          price_monthly?: number | null
          price_yearly?: number | null
          quota_images_per_day?: number | null
          quota_storage_gb?: number | null
          quota_text_requests_per_day?: number | null
          quota_videos_per_day?: number | null
          stripe_price_id_monthly?: string | null
          stripe_price_id_yearly?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          display_name?: string
          features?: Json | null
          id?: string
          is_active?: boolean | null
          name?: string
          price_monthly?: number | null
          price_yearly?: number | null
          quota_images_per_day?: number | null
          quota_storage_gb?: number | null
          quota_text_requests_per_day?: number | null
          quota_videos_per_day?: number | null
          stripe_price_id_monthly?: string | null
          stripe_price_id_yearly?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      roxy_catalog_items: {
        Row: {
          category_id: string
          company_id: string
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          name: string
          price: number
          type: string
          unit: string | null
        }
        Insert: {
          category_id: string
          company_id: string
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name: string
          price?: number
          type: string
          unit?: string | null
        }
        Update: {
          category_id?: string
          company_id?: string
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name?: string
          price?: number
          type?: string
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "roxy_catalog_items_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "roxy_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roxy_catalog_items_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "roxy_companies"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_categories: {
        Row: {
          company_id: string
          created_at: string
          id: string
          name: string
          type: string
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          name: string
          type: string
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          name?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "roxy_categories_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "roxy_companies"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_companies: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          owner_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "roxy_companies_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "roxy_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_enquiries: {
        Row: {
          client_id: string
          created_at: string
          id: string
          notes: string | null
          status: string
        }
        Insert: {
          client_id: string
          created_at?: string
          id?: string
          notes?: string | null
          status?: string
        }
        Update: {
          client_id?: string
          created_at?: string
          id?: string
          notes?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "roxy_enquiries_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "roxy_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_enquiry_line_items: {
        Row: {
          catalog_item_id: string
          company_id: string
          created_at: string
          enquiry_id: string
          id: string
          notes: string | null
          quantity: number
        }
        Insert: {
          catalog_item_id: string
          company_id: string
          created_at?: string
          enquiry_id: string
          id?: string
          notes?: string | null
          quantity?: number
        }
        Update: {
          catalog_item_id?: string
          company_id?: string
          created_at?: string
          enquiry_id?: string
          id?: string
          notes?: string | null
          quantity?: number
        }
        Relationships: [
          {
            foreignKeyName: "roxy_enquiry_line_items_catalog_item_id_fkey"
            columns: ["catalog_item_id"]
            isOneToOne: false
            referencedRelation: "roxy_catalog_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roxy_enquiry_line_items_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "roxy_companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roxy_enquiry_line_items_enquiry_id_fkey"
            columns: ["enquiry_id"]
            isOneToOne: false
            referencedRelation: "roxy_enquiries"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_profiles: {
        Row: {
          created_at: string
          email: string | null
          full_name: string
          id: string
          phone: string | null
          role: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          full_name?: string
          id: string
          phone?: string | null
          role: string
        }
        Update: {
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          phone?: string | null
          role?: string
        }
        Relationships: []
      }
      roxy_quote_line_items: {
        Row: {
          created_at: string
          discount_percent: number
          enquiry_line_item_id: string | null
          id: string
          name: string
          quantity: number
          quote_id: string
          unit_price: number
        }
        Insert: {
          created_at?: string
          discount_percent?: number
          enquiry_line_item_id?: string | null
          id?: string
          name: string
          quantity?: number
          quote_id: string
          unit_price?: number
        }
        Update: {
          created_at?: string
          discount_percent?: number
          enquiry_line_item_id?: string | null
          id?: string
          name?: string
          quantity?: number
          quote_id?: string
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "roxy_quote_line_items_enquiry_line_item_id_fkey"
            columns: ["enquiry_line_item_id"]
            isOneToOne: false
            referencedRelation: "roxy_enquiry_line_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roxy_quote_line_items_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "roxy_quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_quote_revisions: {
        Row: {
          created_at: string
          id: string
          is_current: boolean
          label: string | null
          quote_id: string
          version: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_current?: boolean
          label?: string | null
          quote_id: string
          version: string
        }
        Update: {
          created_at?: string
          id?: string
          is_current?: boolean
          label?: string | null
          quote_id?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "roxy_quote_revisions_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "roxy_quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      roxy_quotes: {
        Row: {
          business_user_id: string
          company_id: string
          created_at: string
          enquiry_id: string
          id: string
          notes: string | null
          status: string
          tax_rate_percent: number
          terms: string | null
          updated_at: string
        }
        Insert: {
          business_user_id: string
          company_id: string
          created_at?: string
          enquiry_id: string
          id?: string
          notes?: string | null
          status?: string
          tax_rate_percent?: number
          terms?: string | null
          updated_at?: string
        }
        Update: {
          business_user_id?: string
          company_id?: string
          created_at?: string
          enquiry_id?: string
          id?: string
          notes?: string | null
          status?: string
          tax_rate_percent?: number
          terms?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "roxy_quotes_business_user_id_fkey"
            columns: ["business_user_id"]
            isOneToOne: false
            referencedRelation: "roxy_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roxy_quotes_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "roxy_companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roxy_quotes_enquiry_id_fkey"
            columns: ["enquiry_id"]
            isOneToOne: false
            referencedRelation: "roxy_enquiries"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean | null
          canceled_at: string | null
          created_at: string | null
          current_period_end: string | null
          current_period_start: string | null
          id: string
          org_id: string
          plan_id: string
          status: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string | null
        }
        Insert: {
          cancel_at_period_end?: boolean | null
          canceled_at?: string | null
          created_at?: string | null
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          org_id: string
          plan_id: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string | null
        }
        Update: {
          cancel_at_period_end?: boolean | null
          canceled_at?: string | null
          created_at?: string | null
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          org_id?: string
          plan_id?: string
          status?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "orgs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_counters: {
        Row: {
          created_at: string | null
          gpu_minutes_used: number | null
          id: string
          images_processed: number | null
          org_id: string
          period_end: string
          period_start: string
          storage_bytes: number | null
          text_requests: number | null
          updated_at: string | null
          videos_processed: number | null
        }
        Insert: {
          created_at?: string | null
          gpu_minutes_used?: number | null
          id?: string
          images_processed?: number | null
          org_id: string
          period_end: string
          period_start: string
          storage_bytes?: number | null
          text_requests?: number | null
          updated_at?: string | null
          videos_processed?: number | null
        }
        Update: {
          created_at?: string | null
          gpu_minutes_used?: number | null
          id?: string
          images_processed?: number | null
          org_id?: string
          period_end?: string
          period_start?: string
          storage_bytes?: number | null
          text_requests?: number | null
          updated_at?: string | null
          videos_processed?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "usage_counters_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "orgs"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          email: string | null
          full_name: string | null
          id: string
          is_active: boolean | null
          is_premium: boolean
          is_superuser: boolean | null
          last_login: string | null
          password_hash: string | null
          updated_at: string | null
          usage_stats: Json
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
          is_active?: boolean | null
          is_premium?: boolean
          is_superuser?: boolean | null
          last_login?: string | null
          password_hash?: string | null
          updated_at?: string | null
          usage_stats?: Json
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
          is_active?: boolean | null
          is_premium?: boolean
          is_superuser?: boolean | null
          last_login?: string | null
          password_hash?: string | null
          updated_at?: string | null
          usage_stats?: Json
          username?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      active_subscriptions_view: {
        Row: {
          current_period_end: string | null
          current_period_start: string | null
          id: string | null
          org_id: string | null
          org_name: string | null
          plan_display_name: string | null
          plan_id: string | null
          plan_name: string | null
          status: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "orgs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      user_org_summary_view: {
        Row: {
          completed_jobs: number | null
          org_id: string | null
          org_name: string | null
          plan_name: string | null
          role: string | null
          subscription_status: string | null
          total_jobs: number | null
          user_id: string | null
          username: string | null
        }
        Relationships: [
          {
            foreignKeyName: "memberships_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "orgs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      get_user_orgs: {
        Args: { user_uuid: string }
        Returns: {
          org_id: string
          org_name: string
          org_slug: string
          user_role: string
        }[]
      }
      roxy_create_enquiry: {
        Args: { items: Json; notes?: string }
        Returns: string
      }
      roxy_business_create_enquiry: {
        Args: { _client_id: string; items: Json; notes?: string }
        Returns: string
      }
      roxy_convert_enquiry_to_quote: {
        Args: {
          _company_id: string
          _enquiry_id: string
          _tax_rate_percent?: number
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
